"""empty message

Revision ID: 690673cf06bb
Revises: 
Create Date: 2022-04-19 16:31:22.603242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690673cf06bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('comentario', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    # ### end Alembic commands ###
